profile:
  store-selected: true
  store-fake-ip: true

geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"

dns:
  enable: true
  respect-rules: false
  ipv6: false
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    'geosite:cn':
    - system
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  direct-nameserver:
    - system
  direct-nameserver-follow-policy: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: rule
  fake-ip-filter:
    - DOMAIN-SUFFIX,googleapis.cn,real-ip
    - GEOSITE,cn,real-ip
    - GEOSITE,gfw,fake-ip
    - MATCH,fake-ip

tcp-concurrent: false
log-level: debug
