dns:
  enable: true
  default-nameserver:
    - 223.5.5.5
    - 119.28.28.28
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  direct-nameserver:
    - system
